name: Achievments Metrics
on:
  # Run once every month
  schedule:
    - cron: "0 0 1 * *"
  # Run workflow manually
  workflow_dispatch:
  push:
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      ## Achievements
      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
        with:
          filename: Achievments.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
