name: AniList Metrics
on:
  # Run once every month
  schedule:
    - cron: "0 0 1 * *"
  # Run workflow manually
  workflow_dispatch:
  push:
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: AniList
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@v3.32
        with:
          filename: AniList.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: Abdallah
