name: Lichess Metrics
on:
  # Run once every week
  schedule:
    - cron: "0 0 * * 5"
  # Run workflow manually
  workflow_dispatch:
  push:
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Lichess
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@v3.32
        with:
          filename: Lichess.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.LICHESS_TOKEN }}
          plugin_chess_user: AbdallahMehiz
          plugin_chess_platform: lichess.org
