name: Metrics
on:
  # Run every Friday night
  schedule: [{ cron: "0 0 * * 5" }]
  # Run workflow manually
  workflow_dispatch:
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: General.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AbdallahMehiz
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_octicon: yes
          config_timezone: Africa/Lagos
          config_twemoji: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_fortune: yes
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines,bytes-size
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: RusKis
          plugin_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: abdallahmehiz
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_url: Abdallah.Mehiz.xyz
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: AbdallahMehiz
          repositories_forks: yes

      - name: Misc
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: Misc.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          ## Lichess
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.LICHESS_TOKEN }}
          plugin_chess_user: AbdallahMehiz
          plugin_chess_platform: lichess.org
          ## Achievements
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          # Steam
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198930137339"
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_games_limit: 2
          # AniList
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: Abdallah

          #      - name: twitter
          #        if: ${{ success() || failure() }}
          #        uses: lowlighter/metrics@latest
          #        with:
          #          filename: twitter.svg
          #          token: ${{ secrets.METRICS_TOKEN }}
          #          user: AbdallahMehiz
          #          template: classic
          #          base: ""
          #          base_skip: yes
          #          config_timezone: Africa/Algiers
          #          plugin_tweets: yes
          #          plugin_tweets_attachments: yes
          #          plugin_tweets_limit: 2
          #          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          #          plugin_tweets_user: AbdallahMehiz
