name: Twitter Metrics
on:
  # Run once every week
  schedule:
    - cron: "0 0 * * 5"
  # Run workflow manually
  workflow_dispatch:
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: twitter
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: twitter.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AbdallahMehiz
          template: classic
          base: ""
          base_skip: yes
          config_timezone: Africa/Algiers
          plugin_tweets: yes
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 2
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: abdallahmehiz
